# Generated by Django 2.1.3 on 2018-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsAll',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('license_id', models.CharField(max_length=30)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(null=True)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarsIn',
            fields=[
                ('license_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField()),
            ],
        ),
    ]
